clear all
close all
clc

addpath('lib/export_fig')

datasets = { ...
    6,'synthetic_control'           ,8,50,... % 1
    3,'Trace'                       ,2,20,...
    0,'SonyAIBORobotSurfaceII'      ,2,40,...
    0,'SonyAIBORobotSurface'        ,2,20,...
    8,'Symbols'                     ,2,20,... % 5
    5,'TwoLeadECG'                  ,4,30,...
    1,'OliveOil'                    ,2,20,...
    1,'MoteStrain'                  ,4,20,...
    5,'Lighting7'                   ,4,20,...
    6,'Lighting2'                   ,4,30,... % 10
    0,'ItalyPowerDemand'            ,8,50,...
    0,'Gun_Point'                   ,2,40,... % 12
    2,'FaceFour'                    ,4,40,...
    0,'ECGFiveDays'                 ,2,20,...
    0,'ECG200'                      ,2,20,... % 15
    0,'DiatomSizeReduction'         ,2,20,...
    3,'Coffee'                      ,16,30,...
    11,'CBF'                         ,4,50,...
    0,'Beef'                        ,2,20,...
    4,'FISH'                        ,16,30,... % 20
    7,'OSULeaf'                     ,8,50,...
    8,'WordsSynonyms'               ,16,40,...
    7,'Cricket_Z'                   ,4,40,...
    3,'Adiac'                       ,4,40,...
    20,'MedicalImages'               ,8,40,... % 25
    2,'SwedishLeaf'                 ,4,40,...
    7,'Cricket_X'                   ,8,40,...
    17,'Cricket_Y'                   ,4,30,...
    2,'Haptics'                     ,8,50,...
    12,'FacesUCR'                    ,16,20,... % 30
    6,'50words'                     ,8,50,...
    1,'CinC_ECG_torso'              ,8,50,...
    14,'InlineSkate'                 ,4,30,...
    3,'FaceAll'                     ,4,50,...
    0,'MALLAT'                      ,2,20,... % 35
    0,'ChlorineConcentration'       ,2,20,...
    2,'yoga'                        ,8,20,...
    4,'Two_Patterns'                ,2,20,...
    1,'wafer'                       ,8,20,...
    4,'uWaveGestureLibrary_X'       ,8,20}; % 40


none = load('tscu_test_none_all.mat');
dtw  = load('tscu_test_dtw_all.mat');
cdtw = load('tscu_test_cdtw_all.mat');
saga = load('tscu_test_saga_all.mat');
ptw  = load('tscu_test_ptw_all.mat');
%
fprintf('%-30s %5s %5s %5s %5s %5s\n',...
    'Dataset','NONE','DTW','CDTW','SAGA','PTW');
mrange=6;
accuracies = zeros(length(mrange),5);
for i=mrange
    dataname = datasets{4*(i-1)+2};
    trnfile = sprintf('../../UCR/%s/%s_TRAIN',dataname,dataname);
    trn = load(trnfile);
    fprintf('%-30s %5.1f %5.1f %5.1f %5.1f %5.1f\n',...
        dataname,...
        none.r{i,1}.perf.OA*100,...
        dtw.r{i,1}.perf.OA*100,...
        cdtw.r{i,1}.perf.OA*100,...
        saga.r{i,1}.perf.OA*100,...
        ptw.r{i,1}.perf.OA*100);
    accuracies(i,:)= [none.r{i,1}.perf.OA*100,...
        dtw.r{i,1}.perf.OA*100,...
        cdtw.r{i,1}.perf.OA*100,...
        saga.r{i,1}.perf.OA*100,...
        ptw.r{i,1}.perf.OA*100];
end

for i=mrange
    dataname = datasets{4*(i-1)+2};
    features = load(sprintf('../../UCR/%s/%s_TRAIN.features',dataname,dataname));
    fprintf('%-30s %5s %5s %5s %5s %5s %5s %5s %5s %5s %5s %5s %5s %5s\n',...
        dataname,'freq','trend','seas','auto','non','skew','kurt',...
        'hurst','lyap','dcaut','dcnon','dcske','dckur');
    labels=unique(features(:,1))';
    for j=labels
        fprintf('%-30d ',j);
        subset=features(features(:,1)==j,2:end);
        fprintf('%5.3f ',mean(subset));
        fprintf('\n');
    end
     fprintf('%-30s ','mean');
        subset=features(:,2:end);
        fprintf('%5.3f ',mean(subset));
        fprintf('\n');
end

a=zeros(length(mrange),15);
cname = {'NONE','DTW','CDTW','SAGA','PTW'};
c = [1 2;1 3;1 4;1 5;2 3;2 4;2 5;3 4;3 5;4 5];

fprintf('%2s %4s %4s %6s %6s %5s %5s %8s %3s %8s %3s %5s %5s %5s %5s %4s\n',...
    'id','MET1','MET2','m1%','m2%','cpu1','cpu2','McNemar','Sgn',...
    'binom','Sgn','FFn00','TFn10','FTn01','TTn11','win');
for i=mrange
    r{1} = none.r{i,1};
    r{2} = dtw.r{i,1};
    r{3} = cdtw.r{i,1};
    r{4} = saga.r{i,1};
    r{5} = ptw.r{i,1};
    
    a(i,1) = r{1}.perf.OA;
    a(i,2) = r{2}.perf.OA;
    a(i,3) = r{3}.perf.OA;
    a(i,4) = r{4}.perf.OA;
    a(i,5) = r{5}.perf.OA;
    
    for j=1:size(c,1)
        s = tscu_significance(r{c(j,1)}.truelabels,r{c(j,1)}.labels,...
            r{c(j,2)}.labels);
        a(i,5+j)=s.ms;
        if s.w
            winner = cname{c(j,s.w)};
        else
            winner = '----';
        end
        fprintf('%2d %4s %4s %5.4f %5.4f %5.0f %5.0f %8.5f %3d %8.5f %3d %5d %5d %5d %5d %4s\n',...
            i,cname{c(j,1)},cname{c(j,2)},...
            r{c(j,1)}.perf.OA, r{c(j,2)}.perf.OA,...
            r{c(j,1)}.classification_time, r{c(j,2)}.classification_time,...
            s.m,s.ms,s.b,s.bs,s.n00,s.n10,s.n01,s.n11,winner);  
    end
end

% for i=1:m
%     fprintf('%5.4f ',a(i,1:5));
%     fprintf('%d ',a(i,6:end));
%     fprintf('\n');
% end

% for j=1:size(c,1)
%     snot = find(a(:,5+j)==0);
%     s    = find(a(:,5+j)==1);
%     d    = a(:,c(j,2))-a(:,c(j,1));
%     % NONE vs DTW
%     %d = x(:,2)-x(:,1); % DTW - NONE
%     m1=cname{c(j,1)};
%     m2=cname{c(j,2)};
%     plot(sort(d(s)),s,'ks','MarkerSize',12);
%     hold on;
%     plot(sort(d(snot)),snot,'k+','MarkerSize',12);
%     plot([0 0],[0 41],'k--');
%     legend('Significant','Other','Location','NorthWest'); ylim([0 41]); xlim([-0.20 0.20]);
%     ylabel('Dataset index','FontSize',12);
%     xlabel('Difference between accuracies','FontSize',12);
%     set(gca,'YTick',[]);
%     title(sprintf('%s .vs. %s',cname{c(j,1)},cname{c(j,2)}));
%     set(gca,'XTick',[-0.1 0 0.1],'XTickLabel',...
%         {sprintf('%s< %s',m2,m1),...
%         sprintf('%s = %s',m2,m1),...
%         sprintf('%s > %s',m2,m1)},'FontSize',10);
%     export_fig('-pdf','-transparent',...
%         sprintf('tscu_test_all_%s_vs_%s.pdf',m1,m2));
%     hold off;
% end
